### ISSUE TITLE
ncurses

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#1]
I terminali permettono di essere gestiti in
modalità semigrafica.
La cosa risulta però difficoltosa (e noiosa).
Inoltre non tutti i terminali sono uguali
e ciò che funziona su uno potrebbe non funzionare
su un altro.

Le librerie ncurses (new curses) nascondono
queste difficoltà mettendo a disposizione
delle funzioni più semplici e che sono
indipendenti dal terminale.

Dai un'occhiata al file C/hello/hello.c

**Comment by TeoColuccio** [comment]
Ok ho fatto, solo perché devo aggiungere la libreria a mano tramite il
compilatore? Non se la può andare a prendere automaticamente visto che ho
fatto un include?

2016-12-09 20:14 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
c'è il Makefile

**Comment by TeoColuccio** [comment]
Ah okk

2016-12-09 20:54 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Guarda come stampare in una posizione a scelta.
Inoltre quando non serve si puo' "spegnere il cursore".

**Comment by TeoColuccio** [comment]
Okk

2016-12-09 20:58 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
guarda come ottenere le dimensioni del terminale

**Comment by TeoColuccio** [comment]
Okk

2016-12-09 21:09 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Si possono usare le ncurses anche in Python
