### ISSUE TITLE
input

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#10]
usa getch() della libreria ncurses. Ora non ti serve più la gestione dell'input che facevi prima

**Comment by FabioZTessitore** [comment]
la pulizia della riga va fatta prima di chiedere l'input

**Comment by TeoColuccio** [comment]
Quindi devo pulire guess subito prima di chiedere l'input?

**Comment by TeoColuccio** [comment]
Dovrei mettere un while ((guess=getch()) != '\n') ;  ?

**Comment by FabioZTessitore** [comment]
lo vedi che non hai capito come si fa l'input?

**Comment by TeoColuccio** [comment]
Mica c'era questo casino negli esempi che mi avete inviato?

**Comment by FabioZTessitore** [comment]
il "casino" lo stai facendo tu, la soluzione è semplicissima

**Comment by TeoColuccio** [comment]
Ora pulisco la riga prima di chiedere guess.

**Comment by FabioZTessitore** [comment]
andiamo avanti, poi ci ritorniamo. passa ai moduli guess e guess_nc

**Comment by TeoColuccio** [comment]
Prof ora uso dappertutto scanw e getch al posto di scanf e getchar..

**Comment by FabioZTessitore** [comment]
ora però dovresti usarle bene, hai solo cambiato i nomi

**Comment by TeoColuccio** [comment]
Così le a avete usate voi nell'esempio

**Comment by FabioZTessitore** [comment]
Ma quando mai

**Comment by TeoColuccio** [comment]
Prof ma se sono equivalenti a getch e getchar perché non posso usarle allo stesso modo? E comunque così sono utilizzate nell'esempio.

**Comment by FabioZTessitore** [comment]
Fammi capire in cosa la gestione dell'input che ti ho inviato è uguale a quella che hai nel codice

ps. equivalenti significa che se getchar accetta un carattere, anche getch accetta un carattere. Ma non sono uguali, non si comportano allo stesso modo.
Come vedi la domanda che ti avevo fatto sul codice di esempio era più che sensata ;)

```c
/* input.c */

/* input di caratteri */

#include <ncurses.h>

int main()
{
  int car;      /* carattere letto */

  initscr();
  curs_set(0);  /* rende invisibile il cursore */
  noecho();     /* rende invisibili i caratteri digitati dall'utente */

  mvprintw(3, 5, "Digita un carattere:");

  car = getch();
  mvprintw(7, 5, "Hai digitato %c", car);
  refresh();

  mvprintw(10, 5, "Digita un altro carattere:");
  car = getch();
  mvprintw(14, 5, "Hai digitato %c", car);

  mvprintw(18, 5, "Premi un tasto per uscire");
  refresh();

  getch();

  endwin();

  return 0;
}
```

**Comment by TeoColuccio** [comment]
Ma cosa c'è di difficile? Nell'esempio assegnate alla variabile car un valore letto da tastiera tramite la funzione getch e poi la stampate con mvprintw.

**Comment by FabioZTessitore** [comment]
e poi?

**Comment by TeoColuccio** [comment]
Il refresh, ma fa parte della stampa.

**Comment by FabioZTessitore** [comment]
no

**Comment by TeoColuccio** [comment]
Niente più.

**Comment by FabioZTessitore** [comment]
appunto. e il tuo codice è così?

**Comment by TeoColuccio** [comment]
`      while ((guess = getch() != '\n'))       /* devi aggiustare tutti questi input */
        ;                                     /* ora hai a disposizione le ncurses */
      scanw("%d\n", &guess);`
Nel ciclo c'è solo la condizione in più.. per la pulizia.

**Comment by FabioZTessitore** [comment]
e non serve

**Comment by TeoColuccio** [comment]
La pulizia o la condizione? E in ogni caso, come pulisce?

**Comment by FabioZTessitore** [comment]
non devi pulire niente, ci pensa ncurses

**Comment by TeoColuccio** [comment]
Ho fatto qualche modifica

**Comment by FabioZTessitore** [comment]
devi togliere stdio.h e va bene
(forse ci vuole qualche aggiustamento nella visualizzazione dell'output, ma cose estetiche)
