### ISSUE TITLE
guess_nc

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#11]
il modulo guess_nc deve stare "sopra" al modulo guess. Il che significa che guess deve fornire le stringhe da stampare.

**Comment by TeoColuccio** [comment]
Come ho fatto con guess_stampa_intestazione()?

**Comment by FabioZTessitore** [comment]
ok

**Comment by TeoColuccio** [comment]
Ho ritoccato guess_check()

**Comment by FabioZTessitore** [comment]
perché ritorna int?

**Comment by TeoColuccio** [comment]
Errore di distrazione, subito corretto

**Comment by TeoColuccio** [comment]
Prof e ora?

**Comment by FabioZTessitore** [comment]
ho messo qualche suggerimento nel codice

**Comment by TeoColuccio** [comment]
Credo di aver corretto tutto tranne l'input ovviamente.

**Comment by FabioZTessitore** [comment]
ho messo qualche altro suggerimento. ovviamente non avevi corretto tutto

**Comment by TeoColuccio** [comment]
Era normale amministrazione..

**Comment by TeoColuccio** [comment]
Prof li ho fatti questi aggiustamenti..

**Comment by FabioZTessitore** [comment]
ok, passiamo al main
