### ISSUE TITLE
quadrati colorati

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#13]
![quadrati](https://cloud.githubusercontent.com/assets/3002194/21858072/028e296c-d828-11e6-9f00-ad516c777ae6.png)

**Comment by TeoColuccio** [comment]
Prof teoricamente dovrebbe andare..

**Comment by FabioZTessitore** [comment]
a me non stampa niente

**Comment by TeoColuccio** [comment]
Infatti ho detto "teoricamente".. Comunque il problema è nell'input, perché se setto il colore manualmente nella funzione va benissimo.

**Comment by TeoColuccio** [comment]
Come dicevo il problema è quel maledetto input con getch().

**Comment by FabioZTessitore** [comment]
Però hai individuato il responsabile. Metti delle stampe con print. Fatti
stampare il valore, il tipo in varie parti del programma e vedi dove nasce
il problema

Il 12 gen 2017 7:00 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Faccio un debug manuale.. Ottima idea

**Comment by FabioZTessitore** [comment]
Così si fa

Il 12 gen 2017 7:06 PM, "Teodoro" <notifications@github.com> ha scritto:

**Comment by TeoColuccio** [comment]
Mica me l'avevate detto che getch() transforma gli input in int... Ma comunque per stampare la variabile color, per provare, sono stato costretto ad usare il semplice print(). Non ho trovato il modo per stamparla con addstr().

**Comment by FabioZTessitore** [comment]
ho messo dei suggerimenti

**Comment by TeoColuccio** [comment]
Alla fine posso stampare una variabile con addstr?
