### ISSUE TITLE
menu

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#14]
![menu](https://cloud.githubusercontent.com/assets/3002194/21933711/c1bac226-d9a6-11e6-8f9b-40fe210c7b8e.png)

**Comment by FabioZTessitore** [comment]
passiamo al menu

**Comment by TeoColuccio** [comment]
Altissimo livello!

**Comment by FabioZTessitore** [comment]
ok, per confronto ti ho caricato la mia versione.
dai un'occhiata al menu

**Comment by TeoColuccio** [comment]
Bene

2017-01-17 19:54 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
