### ISSUE TITLE
led

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#15]
![led](https://cloud.githubusercontent.com/assets/3002194/22035063/df103234-dcee-11e6-8fbd-348e21612207.png)

**Comment by TeoColuccio** [comment]
Questo sono curioso di vederlo fatto da voi..

**Comment by FabioZTessitore** [comment]
i tuoi led non si spengono

**Comment by TeoColuccio** [comment]
Eh lo so.. come faccio a farli spegnere?? Lo so anche fare, ma viene un codice lungo..

**Comment by TeoColuccio** [comment]
Il main si potrebbe rimpicciolire ancor di più, creando una funzione led_on_off() solo per vedere la scelta e poi usare le funzioni già create che, a seconda dello stato, accendono o spengono il led scelto.. Ma non credo sia necessario.
