### ISSUE TITLE
attributi

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#4]
I caratteri possono essere visualizzati
con vari effetti speciali (es. sottolineato, grassetto, ecc.).
Le librerie ncurses utilizzano gli attributi
per modificare le caratteristiche del testo.

Dai un'occhiata al file C/attrs/attrs.c

**Comment by TeoColuccio** [comment]
Okk

2016-12-10 17:06 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
vedi i colori

**Comment by FabioZTessitore** [comment]
i colori standard possono essere modificati
se il terminale risponde true a can_change_color().
Nel caso, si usa init_color(COLOR_RED, 1000, 700, 700) (crea un rosa)
Attenzione: tutte le stringhe stampate in rosso diventeranno rosa
anche quelle stampate in precedenza!

**Comment by FabioZTessitore** [comment]
vedi C/chgat/chgat.c
per vedere come modificare attributi e colori
di caratteri già scritti

**Comment by FabioZTessitore** [comment]
Attributi e colori in Python
vedi Python/attr_color/attr_color.py
