### ISSUE TITLE
Quadrati

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#5]
disegna vari quadrati con le ncurses

![schermata da 2016-12-11 12-01-30](https://cloud.githubusercontent.com/assets/3002194/21079675/a976f33c-bf99-11e6-8ed1-39d6832af39d.png)

**Comment by FabioZTessitore** [comment]
fare una funzione (magari in un modulo) pareva brutto?

**Comment by TeoColuccio** [comment]
Per fare il ciclo uso una funzione?

2016-12-11 20:07 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
Dovresti fare una funzione per eseguire un compito, ad esempio disegnare un
quadrato

Il domenica 11 dicembre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
1) si scrive draw con la 'a'
2) perché metti il controllo sui colori in init() e start_color in square()

**Comment by TeoColuccio** [comment]
Ho creato una nuova funzione.

2016-12-12 17:15 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
```
init_pair(1, COLOR_BLACK, COLOR_WHITE);
init_pair(2, COLOR_BLACK, COLOR_GREEN);  
```
devi spostare queste righe, fanno parte dell'inizializzazione (poi ti spiego meglio)

**Comment by FabioZTessitore** [comment]
quindi ora viene chiamata prima start_color() e poi viene fatto il controllo se ci sono i colori

**Comment by TeoColuccio** [comment]
L'ho notato anche io, sto prevedendo ad ordinare.

Il mercoledì 14 dicembre 2016, Fabio Z Tessitore <notifications@github.com>
ha scritto:

**Comment by FabioZTessitore** [comment]
non ci siamo

**Comment by TeoColuccio** [comment]
Come mai?

**Comment by FabioZTessitore** [comment]
non ha senso che init_scr() non sia la prima funzione chiamata

**Comment by FabioZTessitore** [comment]
ti stai perdendo in un bicchier d'acqua. perché non fai una sola funzione di inizializzazione?

quello che mi interessava di questo programma era farti creare un modulo per la stampa di quadrati che poi devi riutilizzare per la scacchiera

**Comment by TeoColuccio** [comment]
Ahah ora va bene?
ps per una volta che ho provato ad usare windows e la sua bash ubuntu mi ha
ritornato la famosa frase "il terminale non riesce a gestire i colori"

Il giorno 14 dicembre 2016 15:51, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
non ce la posso fare
riguardati draw_init() a mente fresca

**Comment by TeoColuccio** [comment]
Cosa c'è di male? Controllo se il terminale riesce a gestire i colori, se
così è inizializzo tutto..


2016-12-15 0:05 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
e se non riesce?

**Comment by TeoColuccio** [comment]
C'è quel exit().

**Comment by FabioZTessitore** [comment]
il problema non è exit

**Comment by TeoColuccio** [comment]
Ma se non riesce a gestire i colori esegue tutto l'if. Non vedo il problema

2016-12-16 16:48 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
endwin non lo vedi?

**Comment by TeoColuccio** [comment]
Non pensavo ce l'avessi messo io..

2016-12-16 16:58 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ci stanno i fantasmi?

**Comment by TeoColuccio** [comment]
Ma quel blocco l'ho copiato pari pari da quello che avete scritto voi.
Perché avrei dovuto modificarlo? Bhoo i mostri..

2016-12-16 18:09 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ma io lo metto dopo l'init

**Comment by TeoColuccio** [comment]
Mha forse è capitata qualche copia selvaggia..

2016-12-16 18:14 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
vabbé aggiusta e andiamo avanti

**Comment by TeoColuccio** [comment]
Già fatto

2016-12-16 18:25 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
falso

**Comment by FabioZTessitore** [comment]
mi arrendo

**Comment by TeoColuccio** [comment]
Prof ma veramente? Quell'endwin era giusto. Avete detto voi che era un
problema..

2016-12-16 18:40 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by TeoColuccio** [comment]
Vogliamo chiudere questa questione?

2016-12-16 19:12 GMT+01:00 Teodoro Coluccio <teodoro.coluccio@gmail.com>:

**Comment by FabioZTessitore** [comment]
vatti a vedere i programmi di esempio

**Comment by FabioZTessitore** [comment]
hai dimenticato di rimettere endwin()
