### ISSUE TITLE
scacchiera

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#6]
![schermata da 2016-12-11 12-01-50](https://cloud.githubusercontent.com/assets/3002194/21079678/b5c8fd06-bf99-11e6-86a2-db1f7a5a858e.png)

**Comment by FabioZTessitore** [comment]
Usa il modulo quadrato per disegnare la scacchiera

**Comment by TeoColuccio** [comment]
Mo è altissimo livello!

**Comment by FabioZTessitore** [comment]
saliamo un altro po'
1. il modulo scacchiera è il modulo quadrato
2. il modulo scacchiera dovrebbe avere una funzione che fa la stampa dei quattro quadrati
3. il modulo scacchiera dovrebbe avere un'altra funzione per la stampa della scacchiera intera
