### ISSUE TITLE
input

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#7]
Ho aggiunto la directory input_num

Le funzioni per l'input sono:

scanw(): equivalente di scanf()
getch(): equivalente di getchar(), legge un carattere
getstr(): equivalente di gets(), legge una stringa

**Comment by TeoColuccio** [comment]
Ok. Mentre quando attiviamo lo STANDOUT che cambia??

**Comment by FabioZTessitore** [comment]
ma allora non studi, stava nelle prime cose su ncurses

**Comment by TeoColuccio** [comment]
Oddio, vi giuro che ricordavo il grassetto e il sottolineato.. l'evidenzato mi era sfuggito..

**Comment by FabioZTessitore** [comment]
ho caricato input caratteri

**Comment by TeoColuccio** [comment]
Ok facile

**Comment by FabioZTessitore** [comment]
Sicuro che hai capito il senso?

**Comment by TeoColuccio** [comment]
Non mi sembra ci sia molto da capire..

**Comment by FabioZTessitore** [comment]
lo vedremo con gli esercizi haha

**Comment by FabioZTessitore** [comment]
ho caricato tasti funzione

**Comment by TeoColuccio** [comment]
Ok sembra facile.. Appena possibile faccio guess

2016-12-24 12:40 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:
