### ISSUE TITLE
guess

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/ncurses#8]
ricarica guess in una cartella
e diamogli un'interfaccia ncurses

![guess1](https://cloud.githubusercontent.com/assets/3002194/21466829/b0c174f4-c9d6-11e6-9e23-3539659b5c8f.png)

![guess2](https://cloud.githubusercontent.com/assets/3002194/21466830/b1c8eed6-c9d6-11e6-8435-44e40b2ef474.png)

**Comment by TeoColuccio** [comment]
Il programma che ho caricato funziona quasi... come faccio a far sovrascrivere una riga?

**Comment by FabioZTessitore** [comment]
puoi semplicemente scrivere nella stessa posizione. Ricordati di aggiungere un \n per cancellare il resto della linea

**Comment by FabioZTessitore** [comment]
cerca di usare i moduli random e guess che avevi senza modificarli. Poi crei un altro modulo guess_nc. Sennò è stato inutile creare guess

**Comment by TeoColuccio** [comment]
Ma perché non sovrascrive il numero che inserisco? Il \n l'ho messo..
E anche la scritta della vincita..
